### ISSUE TITLE
Anker bSOL launch checklist

### ISSUE THREAD

**Issue by ruuda** [ChorusOne/solido#503]
* [ ] Create the bSOL mint on Solana mainnet
* [ ] Get bSOL listed in [the token list](https://github.com/solana-labs/token-list)
* [ ] Ensure stSOL-UST pool exists on Orca
* [ ] Ensure there is some amount of initial liquidity in the stSOL-UST pool
* [ ] Deploy Anker program
* [ ] Have multisig members reproduce the build of the Anker program and verify the deployment
* [ ] Create Anker instance. This depends on the following inputs:
    * [ ] Address of stSOL/UST pool on Orca.
    * [ ] Terra mainnet rewards destination address.
    * [ ] bSOL mint
* [ ] Deploy frontend
* [ ] Deploy new version of maintenance bot
* [ ] Ensure documentation of the full process is available (from depositing on Solana to putting the bSOL in Anchor on Terra)
* [ ] Ensure announcements are ready
    * [ ] Terra Twitter
    * [ ] Lido Twitter
    * [ ] Chorus One blog

**Comment by enriquefynn** [comment]
bSOL mint created on 23 February 2022:
<pre>
bSOL mint:             EbMg3VYAE9Krhndw7FuogpHNcEPkXVhtXr7mGisdeaur
Wrapped bSOL on Terra: terra1c3xd5s2j3ejx2d94tvcjfkrdeu6rmz48ghzznj
</pre>

**Comment by ruuda** [comment]
We have a Solana devnet deployment of 7a05389870acf42740762fe91994a9fa4edb74e2 at the following address:

```
Anker address:         E1dKiT26QDzhbtfUL2WdRumE6AqDTiwc3aLcL3Fb8RdE
Anker program id:      DM42MVcQPzJKTwkaEye2vJCyzzZSWo7joViherWFz7TG
Solido address:        8sqs4Jzs8uq7CEtimhXf32gioVUN3n5Qk65YMkNU5E4F
Solido program id:     CbxVmURN74QZGuFj6qKjM8VDM8b8KKZrbPFLM2CC2hC8
Rewards destination:   terra10w0kh86wqkylhpuwshtqp48qe6545a2ptmzkwg
bSOL mint:             BSo147oW1Nd2AmVKHCgEz9hGAQ9zZLqZWTAXp3p3gxPQ
bSOL mint authority:   C1QSjZ8KxPmtkMkoCezCJC4iUNdNw15ETU7ShUvi5EE3
bSOL supply:           4.440000000 bSOL
Reserve authority:     E8Ku3F6QYNeLxtnkgRPUn2KsJa1MJStE75VFCDoJ7wZd
stSOL reserve address: FygzXCTzNg3cmn6PEypuybkKBewRDi3fcfAf2Nguy6M6
stSOL reserve balance: 4.440000000 stSOL
stSOL reserve value:   Undefined; does Solido have nonzero deposits?
UST reserve address:   G3kFufhrZJGQ6jGNYPvLH84M81XH2Y9x9neKHwJxaD4B
UST reserve balance:   0.000000 UST
```
